{
 "title": "My_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of I/O operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_disk_io_now{device=\"sda\", job=\"node-exporter\", instance=\"node-exporter:9100\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -(avg by(instance) (irate(node_cpu_seconds_total{instance=\"node-exporter:9100\", mode=\"idle\"}[5m]))) * 100"
    }
   ]
  },
  {
   "title": "Data",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\",device=\"/dev/sda3\",fstype=\"btrfs\",mountpoint=\"/\"} / 1024 / 1024 / 1024"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\",device=\"/dev/sda3\",fstype=\"btrfs\",mountpoint=\"/\"} / 1024 / 1024 / 1024 - node_filesystem_avail_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\",device=\"/dev/sda3\",fstype=\"btrfs\",mountpoint=\"/\"} / 1024 / 1024 / 1024"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\",device=\"/dev/sda3\",fstype=\"btrfs\",mountpoint=\"/\"} / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "RAM free",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node-exporter:9100\"} / 1024 / 1024/ 1024"
    }
   ]
  }
 ]
}